#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

unexport MAKEFILE_LIST
MK_NOGENDEPS := $(filter clean,$(MAKECMDGOALS))
override PKGDIR = configPkg
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
C:/ti/xdctools_3_24_05_48/include/utils.tci:
package.mak: C:/ti/xdctools_3_24_05_48/include/utils.tci
C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/xdc.tci:
package.mak: C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/xdc.tci
C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/template.xs:
package.mak: C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/template.xs
C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/om2.xs:
package.mak: C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/om2.xs
C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/xmlgen.xs:
package.mak: C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/xmlgen.xs
C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/xmlgen2.xs:
package.mak: C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/xmlgen2.xs
C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/IPackage.xs:
package.mak: C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/IPackage.xs
C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/package.xs:
package.mak: C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/package.xs
C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/services/global/Clock.xs:
package.mak: C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/services/global/Clock.xs
C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/services/global/Trace.xs:
package.mak: C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/services/global/Trace.xs
C:/ti/xdctools_3_24_05_48/packages/xdc/bld/bld.js:
package.mak: C:/ti/xdctools_3_24_05_48/packages/xdc/bld/bld.js
C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/bld/BuildEnvironment.xs:
package.mak: C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/bld/BuildEnvironment.xs
C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/bld/PackageContents.xs:
package.mak: C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/bld/PackageContents.xs
C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/bld/_gen.xs:
package.mak: C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/bld/_gen.xs
C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/bld/Library.xs:
package.mak: C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/bld/Library.xs
C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/bld/Executable.xs:
package.mak: C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/bld/Executable.xs
C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/bld/Repository.xs:
package.mak: C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/bld/Repository.xs
C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/bld/Configuration.xs:
package.mak: C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/bld/Configuration.xs
C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/bld/Script.xs:
package.mak: C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/bld/Script.xs
C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/bld/Manifest.xs:
package.mak: C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/bld/Manifest.xs
C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/bld/Utils.xs:
package.mak: C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/bld/Utils.xs
C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/bld/ITarget.xs:
package.mak: C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/bld/ITarget.xs
C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/bld/ITarget2.xs:
package.mak: C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/bld/ITarget2.xs
C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/bld/ITargetFilter.xs:
package.mak: C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/bld/ITargetFilter.xs
C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/bld/package.xs:
package.mak: C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/bld/package.xs
package.mak: config.bld
C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/ti/targets/ITarget.xs:
package.mak: C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/ti/targets/ITarget.xs
C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/ti/targets/C28_large.xs:
package.mak: C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/ti/targets/C28_large.xs
C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/ti/targets/C28_float.xs:
package.mak: C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/ti/targets/C28_float.xs
C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/ti/targets/package.xs:
package.mak: C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/ti/targets/package.xs
C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/ti/targets/arm/IArm.xs:
package.mak: C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/ti/targets/arm/IArm.xs
C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/ti/targets/arm/package.xs:
package.mak: C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/ti/targets/arm/package.xs
C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/ti/targets/arm/elf/IArm.xs:
package.mak: C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/ti/targets/arm/elf/IArm.xs
C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/ti/targets/arm/elf/package.xs:
package.mak: C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/ti/targets/arm/elf/package.xs
package.mak: package.bld
C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/tools/configuro/template/compiler.opt.xdt:
package.mak: C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/tools/configuro/template/compiler.opt.xdt
C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/services/io/File.xs:
package.mak: C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/services/io/File.xs
C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/services/io/package.xs:
package.mak: C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/services/io/package.xs
C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/tools/configuro/template/custom.mak.exe.xdt:
package.mak: C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/tools/configuro/template/custom.mak.exe.xdt
C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/tools/configuro/template/package.xs.xdt:
package.mak: C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/xdc/tools/configuro/template/package.xs.xdt
endif

ti.targets.arm.elf.M4F.rootDir ?= C:/ti/ccsv5/tools/compiler/arm_5.0.1
ti.targets.arm.elf.packageBase ?= C:/ti/mcusdk_1_00_01_74/products/xdctools_3_23_05_61/packages/ti/targets/arm/elf/
.PRECIOUS: $(XDCCFGDIR)/%.oem4f
.PHONY: all,em4f .dlls,em4f .executables,em4f test,em4f
all,em4f: .executables,em4f
.executables,em4f: .libraries,em4f
.executables,em4f: .dlls,em4f
.dlls,em4f: .libraries,em4f
.libraries,em4f: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,em4f
	@$(ECHO) xdc .executables,em4f
	@$(ECHO) xdc .libraries,em4f
	@$(ECHO) xdc .dlls,em4f


all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.inc package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.inc package/%_configPkg.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package configPkg" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs $(MK_IDLOPTS) -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

.dlls,em4f .dlls: testio.pem4f

-include package/cfg/testio_pem4f.mak
-include package/cfg/testio_pem4f.cfg.mak
ifeq (,$(MK_NOGENDEPS))
-include package/cfg/testio_pem4f.dep
endif
testio.pem4f: package/cfg/testio_pem4f.xdl
	@


ifeq (,$(wildcard .libraries,em4f))
testio.pem4f package/cfg/testio_pem4f.c: .libraries,em4f
endif

package/cfg/testio_pem4f.c package/cfg/testio_pem4f.h package/cfg/testio_pem4f.xdl: override _PROG_NAME := testio.xem4f
package/cfg/testio_pem4f.c: package/cfg/testio_pem4f.cfg

clean:: clean,em4f
	-$(RM) package/cfg/testio_pem4f.cfg
	-$(RM) package/cfg/testio_pem4f.dep
	-$(RM) package/cfg/testio_pem4f.c
	-$(RM) package/cfg/testio_pem4f.xdc.inc

clean,em4f::
	-$(RM) testio.pem4f
.executables,em4f .executables: testio.xem4f

testio.xem4f: |testio.pem4f

-include package/cfg/testio.xem4f.mak
testio.xem4f: package/cfg/testio_pem4f.oem4f 
	$(RM) $@
	@$(MSG) lnkem4f $@ ...
	$(RM) $(XDCCFGDIR)/$@.map
	$(ti.targets.arm.elf.M4F.rootDir)/bin/armlnk -w -q -u _c_int00 -fs $(XDCCFGDIR)$(dir $@).  -q -o $@ package/cfg/testio_pem4f.oem4f   package/cfg/testio_pem4f.xdl --silicon_version=7M4 --strict_compatibility=on -c -m $(XDCCFGDIR)/$@.map  -l $(ti.targets.arm.elf.M4F.rootDir)/lib/rtsv7M4_T_le_v4SPD16_eabi.lib
	
testio.xem4f: export C_DIR=
testio.xem4f: PATH:=$(ti.targets.arm.elf.M4F.rootDir)/bin/;$(PATH)
testio.xem4f: Path:=$(ti.targets.arm.elf.M4F.rootDir)/bin/;$(PATH)

testio.test test,em4f test: testio.xem4f.test

testio.xem4f.test:: testio.xem4f
ifeq (,$(_TESTLEVEL))
	@$(MAKE) -R -r --no-print-directory -f $(XDCROOT)/packages/xdc/bld/xdc.mak _TESTLEVEL=1 testio.xem4f.test
else
	@$(MSG) running $<  ...
	$(call EXEC.testio.xem4f, ) 
endif

clean,em4f::
	-$(RM) .tmp,testio.xem4f,0,*


clean:: clean,em4f

clean,em4f::
	-$(RM) testio.xem4f
clean:: 
	-$(RM) package/cfg/testio_pem4f.pjt
%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@
testio_pem4f.oem4f,copy : package/cfg/testio_pem4f.oem4f
testio_pem4f.sem4f,copy : package/cfg/testio_pem4f.sem4f

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg .interfaces $(XDCROOT)/packages/xdc/cfg/Main.xs
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_XSOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,configPkg
configPkg.tar: package/package.bld.xml
configPkg.tar: package/package.ext.xml
configPkg.tar: package/package.rel.dot
configPkg.tar: package/build.cfg
configPkg.tar: package/package.xdc.inc
ifeq (,$(MK_NOGENDEPS))
-include package/rel/configPkg.tar.dep
endif
package/rel/configPkg/configPkg/package/package.rel.xml:

configPkg.tar: package/rel/configPkg.xdc.inc package/rel/configPkg/configPkg/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELTAR,package/rel/configPkg.xdc.inc,package/rel/configPkg.tar.dep)


release release,configPkg: all configPkg.tar
clean:: .clean
	-$(RM) configPkg.tar
	-$(RM) package/rel/configPkg.xdc.inc
	-$(RM) package/rel/configPkg.tar.dep

clean:: .clean
	-$(RM) .libraries .libraries,*
clean:: 
	-$(RM) .dlls .dlls,*
#
# The following clean rule removes user specified
# generated files or directories.
#

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
ifeq (,$(wildcard package/external))
    $(shell $(MKDIR) package/external)
endif
endif
clean::
	-$(RMDIR) package

include custom.mak
clean:: 
	-$(RM) package/configPkg.pjt
